// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MeetUp struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	User        *User  `json:"user"`
}

type NewMeetUp struct {
	Title       string `json:"title"`
	Description string `json:"description"`
}

type User struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	Username  string    `json:"username"`
	FirstName string    `json:"firstName"`
	LastName  string    `json:"lastName"`
	Meetups   []*MeetUp `json:"meetups"`
}
